# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ML_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spectrum', models.TextField()),
                ('fruit', models.TextField()),
                ('label', models.IntegerField()),
                ('gps', models.TextField()),
                ('tmstp', models.IntegerField()),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.ML_model')),
            ],
        ),
        migrations.CreateModel(
            name='SP_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vals', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sp_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.SP_model'),
        ),
    ]
