# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='variety',
            field=models.CharField(default='some_variety', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='fruit',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sample',
            name='label',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.ML_Model'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sp_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.SP_Model'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tmstp',
            field=models.TextField(),
        ),
    ]
