# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20160702_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='variety',
        ),
        migrations.AlterField(
            model_name='sample',
            name='gps',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='label',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.ML_Model'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sp_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.SP_Model'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tmstp',
            field=models.DateTimeField(),
        ),
    ]
