# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20160704_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='label_is_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.ML_Model'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sp_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.SP_Model'),
        ),
    ]
