# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20160706_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(verbose_name='/static/images')),
                ('label', models.SmallIntegerField(choices=[(0, 'not ripe'), (1, 'ripe'), (2, 'too ripe')])),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='image_path',
            field=models.FilePathField(null=True, verbose_name='/static/images'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.ML_Model'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sp_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.SP_Model'),
        ),
    ]
